### ISSUE TITLE
Global alerts always dismiss in-sync, rather than after 5 seconds individually.

### ISSUE THREAD

**Issue by alaycock** [tonymamo/getpackup#19]
**Steps to reproduce:**
- Delete a packing list item
- Wait 1 second
- Delete a packing list item

**Expected result:**
Packing list item 1 would disappear 5 seconds after removal.

**Actual result:**
Packing list item 1 disappears 6 seconds after removal, because deleting the second item resets the time.

**Other notes:**
This is likely related to how useTransition works in GlobalAlerts.tsx

**Comment by tonymamo** [comment]
moved ticket to Notion so closing here :)
